
package ca.ubc.med.ws.demo.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "PersonService", targetNamespace = "http://service.demo.ws.med.ubc.ca/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PersonService {


    /**
     * 
     * @param identifier
     * @return
     *     returns ca.ubc.med.ws.demo.service.Person
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPerson", targetNamespace = "http://service.demo.ws.med.ubc.ca/", className = "ca.ubc.med.ws.demo.service.GetPerson")
    @ResponseWrapper(localName = "getPersonResponse", targetNamespace = "http://service.demo.ws.med.ubc.ca/", className = "ca.ubc.med.ws.demo.service.GetPersonResponse")
    public Person getPerson(
        @WebParam(name = "identifier", targetNamespace = "")
        String identifier);

    /**
     * 
     * @param identifier
     * @return
     *     returns java.util.List<ca.ubc.med.ws.demo.service.Person>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPersonList", targetNamespace = "http://service.demo.ws.med.ubc.ca/", className = "ca.ubc.med.ws.demo.service.GetPersonList")
    @ResponseWrapper(localName = "getPersonListResponse", targetNamespace = "http://service.demo.ws.med.ubc.ca/", className = "ca.ubc.med.ws.demo.service.GetPersonListResponse")
    public List<Person> getPersonList(
        @WebParam(name = "identifier", targetNamespace = "")
        String identifier);

}
