
package ca.ubc.med.ws.demo.service;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "PersonServiceService", targetNamespace = "http://service.demo.ws.med.ubc.ca/", wsdlLocation = "file:/C:/Apps/wsdl/PersonServiceService.wsdl")
public class PersonServiceService
    extends Service
{

    private final static URL PERSONSERVICESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(ca.ubc.med.ws.demo.service.PersonServiceService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = ca.ubc.med.ws.demo.service.PersonServiceService.class.getResource(".");
            url = new URL(baseUrl, "file:/C:/Apps/wsdl/PersonServiceService.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/Apps/wsdl/PersonServiceService.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        PERSONSERVICESERVICE_WSDL_LOCATION = url;
    }

    public PersonServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PersonServiceService() {
        super(PERSONSERVICESERVICE_WSDL_LOCATION, new QName("http://service.demo.ws.med.ubc.ca/", "PersonServiceService"));
    }

    /**
     * 
     * @return
     *     returns PersonService
     */
    @WebEndpoint(name = "PersonServicePort")
    public PersonService getPersonServicePort() {
        return super.getPort(new QName("http://service.demo.ws.med.ubc.ca/", "PersonServicePort"), PersonService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PersonService
     */
    @WebEndpoint(name = "PersonServicePort")
    public PersonService getPersonServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.demo.ws.med.ubc.ca/", "PersonServicePort"), PersonService.class, features);
    }

}
